name: aqmamba
img_size: 256
patch_size: 4
in_chans: 3
out_chans: 3
depths_down: [2, 2, 6, 2]
depths_up: [2, 6, 2, 2]
dims_down: [40, 80, 160, 320]
dims_up: [320, 160, 80, 40]
d_state: 16
drop_rate: 0.0
attn_drop_rate: 0.0
drop_path_rate: 0.1
norm_layer: 'layer_norm'
patch_norm: true
use_ape: true
use_gma: true
gma_num_heads: 8
use_cdam: true