test:
  type: 'single_img'
  root_dir: '/DataA/pwz/workshop/Datasets/color_checker7/inp'
  trans_opt:
    transforms:
      - name: 'resize'
        width: 800
        height: 600
      - name: 'to_tensor'