test:
  type: 'paired_img'
  root_dir: '/DataA/pwz/workshop/Datasets/EUVP_Dataset/test_samples'
  inp_dir: 'Inp'
  ref_dir: 'GTr'
  trans_opt:
    additional_targets:
      ref: image
    transforms:
      - name: 'resize'
        width: 224
        height: 224
      - name: 'to_tensor'