train:
  type: 'paired_img'
  root_dir: '/DataA/pwz/workshop/Datasets/EUVP/paired'
  inp_dir: 'trainA'
  ref_dir: 'trainB'
  trans_opt:
    additional_targets:
      ref: image
    transforms:
      - name: 'resize'
        width: 256
        height: 256
      - name: 'to_tensor'
val:
  type: 'paired_img'
  root_dir: '/DataA/pwz/workshop/Datasets/EUVP/paired'
  inp_dir: 'trainA'
  ref_dir: 'trainB'
  trans_opt:
    additional_targets:
      ref: image
    transforms:
      - name: 'resize'
        width: 256
        height: 256
      - name: 'to_tensor'
test:
  type: 'paired_img'
  root_dir: '/DataA/pwz/workshop/Datasets/EUVP_Dataset/test_samples'
  inp_dir: 'Inp'
  ref_dir: 'GTr'
  trans_opt:
    additional_targets:
      ref: image
    transforms:
      - name: 'resize'
        width: 256
        height: 256
      - name: 'to_tensor'