train:
  type: 'paired_img'
  root_dir: '/DataA/pwz/workshop/Datasets/LOL/our485'
  inp_dir: 'low'
  ref_dir: 'high'
  trans_opt:
    additional_targets:
      ref: image
    transforms:
      - name: 'resize'
        width: 256
        height: 256
      - name: 'to_tensor'
val:
  type: 'paired_img'
  root_dir: '/DataA/pwz/workshop/Datasets/LOL/eval15'
  inp_dir: 'low'
  ref_dir: 'high'
  trans_opt:
    additional_targets:
      ref: image
    transforms:
      - name: 'resize'
        width: 256
        height: 256
      - name: 'to_tensor'
test:
  type: 'paired_img'
  root_dir: '/DataA/pwz/workshop/Datasets/LOL/eval15'
  inp_dir: 'low'
  ref_dir: 'high'
  trans_opt:
    additional_targets:
      ref: image
    transforms:
      - name: 'resize'
        width: 256
        height: 256
      - name: 'to_tensor'