train: &train
  root_dir: '/DataA/pwz/workshop/Datasets/LSUI/train'
  inp_dir: 'inp'
  ref_dir: 'ref'
  width: 256
  height: 256
val:
  root_dir: '/DataA/pwz/workshop/Datasets/LSUI/val'
  <<: *train
test:
  root_dir: '/DataA/pwz/workshop/Datasets/LSUI/test'
  <<: *train