train: &train
  root_dir: '/DataA/pwz/workshop/Datasets/LSUI/train'
  inp_dir: 'inp'
  ref_dir: 'ref'
  width: 128
  height: 128
  preprocess: 'random_crop'
val:
  root_dir: '/DataA/pwz/workshop/Datasets/LSUI/val'
  inp_dir: 'inp'
  ref_dir: 'ref'
  width: 256
  height: 256
  preprocess: 'resize'
test:
  type: 'paired_img'
  root_dir: '/DataA/pwz/workshop/Datasets/LSUI/test'
  inp_dir: 'inp'
  ref_dir: 'ref'
  width: 256
  height: 256
  preprocess: 'resize'