train:
  type: 'waternet'
  root_dir: '/DataA/pwz/workshop/Datasets/LSUI/train'
  inp_dir: 'inp'
  ref_dir: 'ref'
  trans_opt:
    additional_targets:
      ref: image
    transforms:
      - name: 'resize'
        width: 256
        height: 256
      - name: 'horizontal_flip'
        p: 0.5
      - name: 'to_tensor'
val:
  type: 'waternet'
  root_dir: '/DataA/pwz/workshop/Datasets/LSUI/val'
  inp_dir: 'inp'
  ref_dir: 'ref'
  trans_opt:
    additional_targets:
      ref: image
    transforms:
      - name: 'resize'
        width: 256
        height: 256
      - name: 'horizontal_flip'
        p: 0.5
      - name: 'to_tensor'
test:
  type: 'waternet'
  root_dir: '/DataA/pwz/workshop/Datasets/LSUI/test'
  inp_dir: 'inp'
  ref_dir: 'ref'
  trans_opt:
    additional_targets:
      ref: image
    transforms:
      - name: 'resize'
        width: 256
        height: 256
      - name: 'to_tensor'