train:
  type: 'paired_img'
  root_dir: '/DataA/pwz/workshop/Datasets/LSUI/train'
  inp_dir: 'inp'
  ref_dir: 'ref'
  trans_opt:
    additional_targets:
      ref: image
    transforms:
      - name: 'resize'
        width: 224
        height: 224
      - name: 'to_tensor'
val:
  type: 'paired_img'
  root_dir: '/DataA/pwz/workshop/Datasets/LSUI/val'
  inp_dir: 'inp'
  ref_dir: 'ref'
  trans_opt:
    additional_targets:
      ref: image
    transforms:
      - name: 'resize'
        width: 224
        height: 224
      - name: 'to_tensor'
test:
  type: 'paired_img'
  root_dir: '/DataA/pwz/workshop/Datasets/LSUI/test'
  inp_dir: 'inp'
  ref_dir: 'ref'
  trans_opt:
    additional_targets:
      ref: image
    transforms:
      - name: 'resize'
        width: 224
        height: 224
      - name: 'to_tensor'