default: &default
  root_dir: ''
  image_dir: 'images'
  mask_dir: 'masks'
  width: 256
  height: 256
  color_map:
    '000000': 'BW'  # Background (waterbody), black
    '0000ff': 'HD'  # Human divers, blue
    '00ff00': 'PF'  # Aquatic plants and sea-grass, green
    '00ffff': 'WR'  # Wrecks and ruins, sky
    'ff0000': 'RO'  # Robots (AUVs/ROVs/instruments), red
    'ff00ff': 'RI'  # Reefs and invertebrates, pink
    'ffff00': 'FV'  # Fish and vertebrates, yellow
    'ffffff': 'SR'  # Sea-floor and rocks, white
train:
  root_dir: '/DataA/pwz/workshop/Datasets/SUIM/train'
  <<: *default
val:
  root_dir: '/DataA/pwz/workshop/Datasets/SUIM/val'
  <<: *default
test:
  root_dir: '/DataA/pwz/workshop/Datasets/SUIM/test'
  <<: *default