train:
  type: 'seg'
  root_dir: '/DataA/pwz/workshop/Datasets/SUIM/train'
  image_dir: 'images'
  mask_dir: 'masks'
  color_map:
    '000000':
      name: 'BW'  # Background (waterbody), black
      id: 0
    '0000ff':
      name: 'HD'  # Human divers, blue
      id: 1
    '00ff00':
      name: 'PF'  # Aquatic plants and sea-grass, green
      id: 2
    '00ffff':
      name: 'WR'  # Wrecks and ruins, sky
      id: 3
    'ff0000':
      name: 'RO'  # Robots (AUVs/ROVs/instruments), red
      id: 4
    'ff00ff':
      name: 'RI'  # Reefs and invertebrates, pink
      id: 5
    'ffff00':
      name: 'FV'  # Fish and vertebrates, yellow
      id: 6
    'ffffff':
      name: 'SR'  # Sea-floor and rocks, white
      id: 7
  trans_opt:
    additional_targets:
      mask: image
    transforms:
      - name: 'resize'
        width: 256
        height: 256
      - name: 'horizontal_flip'
        p: 0.5
      - name: 'to_tensor'
val:
  type: 'seg'
  root_dir: '/DataA/pwz/workshop/Datasets/SUIM/val'
  image_dir: 'images'
  mask_dir: 'masks'
  color_map:
    '000000':
      name: 'BW'  # Background (waterbody), black
      id: 0
    '0000ff':
      name: 'HD'  # Human divers, blue
      id: 1
    '00ff00':
      name: 'PF'  # Aquatic plants and sea-grass, green
      id: 2
    '00ffff':
      name: 'WR'  # Wrecks and ruins, sky
      id: 3
    'ff0000':
      name: 'RO'  # Robots (AUVs/ROVs/instruments), red
      id: 4
    'ff00ff':
      name: 'RI'  # Reefs and invertebrates, pink
      id: 5
    'ffff00':
      name: 'FV'  # Fish and vertebrates, yellow
      id: 6
    'ffffff':
      name: 'SR'  # Sea-floor and rocks, white
      id: 7
  trans_opt:
    additional_targets:
      mask: image
    transforms:
      - name: 'resize'
        width: 256
        height: 256
      - name: 'horizontal_flip'
        p: 0.5
      - name: 'to_tensor'
test:
  type: 'seg'
  root_dir: '/DataA/pwz/workshop/Datasets/SUIM/test'
  image_dir: 'images'
  mask_dir: 'masks'
  color_map:
    '000000':
      name: 'BW'  # Background (waterbody), black
      id: 0
    '0000ff':
      name: 'HD'  # Human divers, blue
      id: 1
    '00ff00':
      name: 'PF'  # Aquatic plants and sea-grass, green
      id: 2
    '00ffff':
      name: 'WR'  # Wrecks and ruins, sky
      id: 3
    'ff0000':
      name: 'RO'  # Robots (AUVs/ROVs/instruments), red
      id: 4
    'ff00ff':
      name: 'RI'  # Reefs and invertebrates, pink
      id: 5
    'ffff00':
      name: 'FV'  # Fish and vertebrates, yellow
      id: 6
    'ffffff':
      name: 'SR'  # Sea-floor and rocks, white
      id: 7
  trans_opt:
    additional_targets:
      mask: image
    transforms:
      - name: 'resize'
        width: 256
        height: 256
      - name: 'to_tensor'