classes:
  -
    color: '000000' # black
    symbol: 'BW'
    desc: 'Background (waterbody)'
    id: 0
  -
    color: '0000ff' # blue
    symbol: 'HD'
    desc: 'Human divers'
    id: 1
  -
    color: '00ff00' # green
    symbol: 'PF'
    desc: 'Aquatic plants and sea-grass'
    id: 2
  -
    color: '00ffff' # aqua
    symbol: 'WR'
    desc: 'Wrecks and ruins'
    id: 3
  -
    color: 'ff0000' # red
    symbol: 'RO'
    desc: 'Robots (AUVs/ROVs/instruments)'
    id: 4
  -
    color: 'ff00ff' # magenta
    symbol: 'RI'
    desc: 'Reefs and invertebrates'
    id: 5
  -
    color: 'ffff00' # yellow
    symbol: 'FV'
    desc: 'Fish and vertebrates'
    id: 6
  -
    color: 'ffffff' # white
    symbol: 'SR'
    desc: 'Sea-floor and rocks'
    id: 7
train:
  type: 'seg'
  root_dir: '/DataA/pwz/workshop/Datasets/SUIM/train'
  image_dir: 'images'
  mask_dir: 'annotations'
  trans_opt:
    additional_targets:
      mask: image
    transforms:
      - name: 'resize'
        width: 256
        height: 256
      - name: 'horizontal_flip'
        p: 0.5
      - name: 'to_tensor'
val:
  type: 'seg'
  root_dir: '/DataA/pwz/workshop/Datasets/SUIM/val'
  image_dir: 'images'
  mask_dir: 'annotations'
  trans_opt:
    additional_targets:
      mask: image
    transforms:
      - name: 'resize'
        width: 256
        height: 256
      - name: 'horizontal_flip'
        p: 0.5
      - name: 'to_tensor'
test:
  type: 'seg'
  root_dir: '/DataA/pwz/workshop/Datasets/SUIM/test'
  image_dir: 'images'
  mask_dir: 'annotations'
  trans_opt:
    additional_targets:
      mask: image
    transforms:
      - name: 'resize'
        width: 256
        height: 256
      - name: 'to_tensor'