name: aqmamba
img_size: 256
patch_size: 4
in_chans: 3
out_chans: 3
depths_down: [2, 2, 6, 2]
depths_up: [2, 6, 2, 2]
dims_down: [80, 160, 320, 640]
dims_up: [640, 320, 160, 80]
use_vss: true
d_state: 16
drop_rate: 0.0
attn_drop_rate: 0.0
drop_path_rate: 0.1
norm_layer: 'layer_norm'
patch_norm: true
use_ape: true
use_gma: true
use_aem: false
gma_num_heads: 8